# Dependabot: keep dependencies up to date
# https://docs.github.com/en/code-security/dependabot
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dev-deps:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier"
          - "typescript"
          - "webpack*"
          - "*vscode*"

  - package-ecosystem: "npm"
    directory: "/vscode"
    schedule:
      interval: "weekly"
    groups:
      dev-deps:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint"
          - "prettier"
          - "typescript"
          - "webpack*"

  - package-ecosystem: "npm"
    directory: "/env-panel"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/docs-panel"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/servers/sidebar"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
